language: java
jdk:
- openjdk8

services:
- docker

after_success:
- docker build -t interface21/openwms-services:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master